routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\Http\Middleware\ByRole;
use App\Http\Middleware\RoleAccessUserVerify;

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('oauth', function() {
    $client = new GuzzleHttp\Client([
        'base_uri' => 'http://159.203.116.109',
    ]);
    $response = $client->post('/oauth/token', [
        'form_params' => [
            'client_id' => 1,
            'client_secret' => 'y4o6EszE8iY89AS7CdX05LphPkMlfKu4w6GGT2b1',
            'grant_type' => 'client_credentials',
        ]
    ]);

    $data = json_decode($response->getBody()->__toString());

    $response = $client->request('GET', '/api/user', [
        'headers' => [
            'Accept' => 'application/json',
            'Authorization' => 'Bearer '. $data->access_token,
        ],
    ]);
    echo $response->getBody();
    die;
});


Route::group(['prefix' => '/role/{role}/{role_id}', 'middleware' => [ByRole::class, 'auth']], function () {

    Route::get('/dashboard', 'RoleController@dashboard')->name('role.dashboard');

    Route::get('/dashboard/data-export/{dataSource}', 'RoleController@dashboardDataExport')->name('roleDashboardDataExport');

    Route::get('/regions', 'RoleController@regions');

    Route::get('/churches', 'RoleController@churches');

    //Route::get('/agencies', 'RoleController@agencies');
	
    Route::group(['prefix' => '/agencies'], function() {
        Route::get('/', 'AgencyController@index')->name('agency.index');
		Route::get('/agency-details', 'AgencyController@agenciesDetails')->name('agency.agencies-details');
		Route::get('/county-details', 'AgencyController@countyDetails')->name('agency.county-details');
		Route::post('/deactivatedAgency', 'AgencyController@deactivatedAgency');
		Route::post('/addEditAgency', 'AgencyController@addEditAgency');
		Route::post('/editAgency', 'AgencyController@editAgency');
		Route::post('/autoPopulateEmailCounty', 'AgencyController@autoPopulateEmailCounty');
		Route::post('/addEditCounty', 'AgencyController@addEditCounty');
		Route::post('/deactivatedCounty', 'AgencyController@deactivatedCounty');
		Route::post('/editCounty', 'AgencyController@editCounty');
		Route::post('/deleteAgencyTier1', 'AgencyController@deleteAgencyTier1');
		Route::post('/deleteAgencyTier2', 'AgencyController@deleteAgencyTier2');
		Route::post('/deleteAgencyTier3', 'AgencyController@deleteAgencyTier3');
		Route::post('/setDeactivateAgency', 'AgencyController@setDeactivateAgency');
    });
	
    Route::get('/communities', 'RoleController@communities');

    Route::get('/contacts', 'RoleController@contacts')->name('role.contacts');
    Route::group(['prefix' => '/contacts/{user}', 'middleware' => RoleAccessUserVerify::class], function() {
        Route::get('/', 'ContactsController@view')->name('contact.view');
        Route::get('edit', 'ContactsController@edit')->name('contact.edit');
        Route::put('/', 'ContactsController@update')->name('contact.update');
        Route::get('deactivate', 'ContactsController@deactivate')->name('contact.deactivate');
        Route::get('activate', 'ContactsController@activate')->name('contact.activate');
    });
    Route::get('/community/{id}', 'CommunityController@show')->name('communityDetail');;

    Route::get('/events', 'RoleController@events');

    Route::get('/finances', 'RoleController@finances');

    Route::get('/implementing-partners', 'RoleController@implementingPartner')->name('role.implementingPartners');
    Route::group(['prefix' => '/implementing-partners/{implementingPartner}'], function() {
        Route::get('/', 'ImplementingPartnersController@show')->name('implementingPartner.view');
        Route::put('/', 'ImplementingPartnersController@update')->name('implementingPartner.update');
        Route::get('deactivate', 'ImplementingPartnersController@deactivate')->name('implementingPartner.deactivate');
        Route::get('activate', 'ImplementingPartnersController@activate')->name('implementingPartner.activate');
        Route::get('/churches-export', 'ImplementingPartnersController@churchesExport')->name('implementingPartner.churchesExport');
        Route::get('/regions-export', 'ImplementingPartnersController@regionsExport')->name('implementingPartner.regionsExport');
        Route::post('/manage-regions', 'ImplementingPartnersController@manageRegions')->name('implementingPartner.manageRegions');
        Route::post('/manage-contacts', 'ImplementingPartnersController@manageContacts')->name('implementingPartner.manageContacts');
        Route::get('/regions/{region}/detach', 'ImplementingPartnersController@regionDetach')->name('implementingPartner.regionDetach');
        Route::get('/contacts-add', 'ImplementingPartnersController@contactsAdd')->name('implementingPartner.contactsAdd');
        Route::get('/contacts-export', 'ImplementingPartnersController@contactsExport')->name('implementingPartner.contactsExport');
        Route::get('/contacts/{user}/detach', 'ImplementingPartnersController@contactDetach')->name('implementingPartner.contactDetach');
    });

    Route::get('/region', 'RoleController@regions');

    Route::get('/requests', 'RoleController@requests');

    //Route::get('/settings', 'RoleController@settings');
	
    Route::group(['prefix' => '/settings'], function() {
        Route::get('/resources', 'ResourceController@resources')->name('resource.resources');
		Route::post('/addEditResources', 'ResourceController@addEditResources');
		Route::post('/editResources', 'ResourceController@editResources');
		Route::post('/deleteResources', 'ResourceController@deleteResources');
		Route::post('/deactivatedResources', 'ResourceController@deactivatedResources');
		Route::post('/deleteCategory', 'ResourceController@deleteCategory');
    });
    Route::get('/states', 'RoleController@states');

    Route::get('/applications', 'RoleController@applications');
});

Route::group(['prefix' => '/enrollment'], function () {

    Route::get('/orientation/church/{church}', 'ChurchEnrollmentController@orientation');

    Route::get('/activate/church/{church}', 'ChurchEnrollmentController@activate');

    Route::post('/activate', 'ChurchEnrollmentController@storeActivation')->name('storeActivation');

    Route::post('/orientation', 'ChurchEnrollmentController@StoreOrientation')->name('StoreOrientation');

    Route::get('/church-to-church/{request_id}/{church_id}', 'ChurchEnrollmentController@churchToChurch');

    Route::get('/contact-to-church/{request_id}/{church_id}', 'ChurchEnrollmentController@contactToChurch')->name('getContact');

    Route::get('/close-request/{request_id}', 'ChurchEnrollmentController@closeRequest');

    Route::post('/close-request', 'ChurchEnrollmentController@storeCloseRequest')->name('storeCloseRequest');

    Route::get('/respond-to-request/{request_id}/{church_id}', 'ChurchEnrollmentController@responseToRequest');

    Route::get('/verify-participation/{request_id}/{church_id}', 'ChurchEnrollmentController@verifyParticipation');

    Route::get('/tier2-app-bg-check-approval', 'ChurchEnrollmentController@tier2AppBgCheckApproval');

    Route::get('/tier2-app-training-update', 'ChurchEnrollmentController@tier2AppTrainingUpdate');

    Route::get('/tier3-bg-check-approval', 'ChurchEnrollmentController@tier3BgCheckApproval');

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public static function getCategories()
	{
		return [
			'0' => ['id' => '1', 'category' => 'Handbook (LDS Church)'], 
			'1' => ['id' => '2', 'category' => 'Consistory (Protestantism)'],
			'2' => ['id' => '3', 'category' => 'Congregationalist polity & Ecclesiastical polity'],
			'3' => ['id' => '4', 'category' => 'Communion (religion)'],
			'4' => ['id' => '5', 'category' => 'Church union'], 
			'5' => ['id' => '6', 'category' => 'Church planting']
		];
	}
	
	public static function deleteCategories($id){
		// Logic to delete the category goes here
		return true;
	}
}

app/Models/Church.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Church extends Model
{
    use SoftDeletes;

    public $dates = ['created_at', 'updated_at', 'tier_1_enrollment_complete_date', 'last_invoice_date', 'deleted_at'];

    protected $guarded = [];

    // TEMP TEMP TEMP - we should import the data so that there IS a primary point person
    // and going forward it should be required, don't just grab the first one if the flag isn't set
    public function primaryPointPerson()
    {
        $users = $this->users;
        foreach($users as $user) {
            if($user->pivot->primary_point_person) {
                return $user;
            }
        }

        return $users->first();
    }

    public function requests()
    {
        return $this->hasManyThrough('App\Models\Request', 'App\Models\RequestRecipient', null, 'id', null, 'request_id');
    }

    public function responses()
    {
        return $this->hasMany('App\Models\Response');
    }

    public function reviews()
    {
        return $this->hasMany('App\Models\ChurchReview');
    }

    public function zipCode()
    {
        return $this->belongsTo('App\Models\ZipCode');
    }

    public function state()
    {
        return $this->belongsTo('App\Models\State');
    }

    public function county()
    {
        return $this->belongsTo('App\Models\County');
    }

    public function region()
    {
        return $this->belongsTo('App\Models\Region', 'state_id', 'state_id');
    }

    public function enrollmentRequest()
    {
        return $this->hasOne(EnrollmentRequest::class, 'church_id');
    }

    public function users()
    {
        return $this->belongsToMany('App\User')->withPivot(
            't1_point_person',
            'primary_point_person',
            't2_point_person',
            't3_point_person',
            'pastor',
            'finance_person'
        );
    }

    //
    public function getTierApproval()
    {
        $tierApproval = array();
        if ($this->tier_1_enrollment_complete) {
            $tierApproval[] = '1';
        }

        if ($this->tier_2_enrollment_complete) {
            $tierApproval[] = '2';
        }

        if ($this->tier_3_enrollment_complete) {
            $tierApproval[] = '3';
        }

        return implode(',', $tierApproval);
    }

    public function status()
    {
        if ($this->tier_1_enrollment_complete) {
            return 'Active';
        } else {
            if ($this->activation_step_2_complete) {
                return 'Step 3';
            } else {
                if ($this->activation_step_1_complete) {
                    return 'Step 2';
                } else {
                    if ($this->has_enrolled) {
                        return 'Step 1';
                    } else {
                        return 'N/A';
                    }
                }
            }
        }
    }

    public function getResponseCountAttribute() {
        return $this->responses->count();
    }

    public function getRequestsMetAttribute() {
        return $this->reviews->where('verify_did_you_help', true)->count();
    }

    /**
     * Returns the church's regional manager
     *
     * @return \App\User
     */
    public function getRegionalManagerAttribute()
    {
        $region = $this->load('region')->region;

        return $region->regionalManager;
    }

    /**
     * Returns the church's primary point person
     *
     * @return \App\User
     */
    public function getPrimaryPointPersonAttribute()
    {

        $users = $this->users;
        foreach($users as $user) {
            if($user->pivot->primary_point_person) {
                return $user;
            }
        }

        return $users->first();
    }

    /**
     * Returns the church's pastor
     *
     * @return \App\User
     */
    public function getPastorAttribute()
    {
        /**
         * @var Collection $users
         */
        $users = $this->users;

        /**
         * @var \App\User $pastor
         */
        $pastor = $users->first(function ($value) {
            return $value->pivot->pastor;
        });

        return $pastor;
    }

    /**
     * @param Builder $builder
     * @return Builder
     */
    public function scopeActivated(Builder $builder)
    {
        return $builder
            ->where('tier_1_enrollment_complete', true)
            ->where('has_enrolled', true);
    }

    /**
     * @param Builder $builder
     * @return Builder
     */
    public function scopePendingActivation(Builder $builder)
    {
        return $builder
            ->where('tier_1_enrollment_complete', false)
            ->where('has_enrolled', true)
            ;//->where('attended_orientation', 1)
    }

    /**
     * @param Builder $builder
     * @param int $years
     * @return \Illuminate\Database\Query\Builder|static
     */
    public function scopeForYears(Builder $builder, $years = 0)
    {
        $minYear = $years > 0
            ? date('Y', strtotime('-' . ($years - 1) .' year'))
            : date('Y');
        return $builder->whereYear('tier_1_enrollment_complete_date', '>=', $minYear);
    }

    /**
     * @param Builder $builder
     * @return Builder
     */
    public function scopeGiving(Builder $builder)
    {
        return $builder->where('giving_amount', '>', 0);
    }
}

resources/views/category/church/index.blade.php
@extends('layouts.table-view')
<style>
    .icon-buttons, .dt-buttons {
        display: flex;
        justify-content: flex-end;
        margin-right: 20px;
    }

    .fa {
        padding: 5px;
    }

    .modal-title, .modal-footer {
        display:flex;
        justify-content: center;
    }


</style>


@section('badges')
    @include('layouts.badges')
@endsection

@section('table')
    <div class="row">
        <div class="icon-buttons">
            <a href="#"><i id="calendar" style="color:teal" class="fa fa-calendar fa-2x"></i></a>
            <a href="#"><i id="functionList" style="color:green" class="fa fa-envelope fa-2x"></i></a>
            <a href="#"><i id="mailto" style="color:red" class="fa fa-envelope-o fa-2x"></i></a>
        </div>
        <div class="col-xs-12">
            <div class="box table-container">
                <div class="box-body table-responsive">
                    <table id="datatable" class="table table-bordered table-striped" width="100%">
                        <thead>
                        <tr>
                            <th>All</th>
                            <th>Date Activated</th>
                            <th>Status</th>
                            <th>Church Name</th>
                            <th>Tier Approval</th>
                            <th>Primary Point Person</th>
                            <th>Phone</th>
                            <th>City</th>
                            <th>ST</th>
                            <th>Last Login</th>
                            <th>Responses</th>
                            <th>Requests Met</th>
                            <th style="display:none">Email</th>
					@if(count(@$columns) != 0)
						@foreach ($columns as $column)
							<th style="display:none">{{ $column }}</th>

						@endforeach
					@endif
                        </tr>
                        </thead>
                        <tbody>
                        @if(count(@$churches) != 0)

                            @foreach($churches as $church)
                                <tr data-id="{{ $church->id }}">
                                    <td><input type="checkbox" name="{{ $church->id }}" value="{{ $church->id }}"></td>
                                    <td class="foo">{{ empty($church->tier_1_enrollment_complete_date) ? '' : $church->tier_1_enrollment_complete_date->format('Y-m-d') }}</td>
                                    <td class="{{'status-'.$church->status()}}">{{$church->status()}}</td>
                                    <td>{{ $church->name }}</td>
                                    <td>{{ $church->getTierApproval() }}</td>
                                    <td>{{$church->primary_point_person ? $church->primary_point_person->full_name : ''}}</td>
                                    <td>{{$church->primary_point_person ? $church->primary_point_person->formatted_phone : ''}}</td>
                                    <td>{{$church->city}}</td>
                                    <td>{{$church->state->abbreviation}}</td>
                                    <td>{{$church->primary_point_person ? $church->primary_point_person->last_login : ''}}</td>
                                    <td>{{$church->response_count}}</td>
                                    <td>{{$church->requests_met}}</td>
                                    <td style="display:none">{{$church->primary_point_person ? $church->primary_point_person->email: ''}}</td>

                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="11">No churches found.</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                    {{$churches->links()}}
                </div>
            </div>
        </div>
    </div>
@endsection





<!-- Modal -->
<div id="functionListModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Select the function from the drop-down below.</h4>
            </div>
            <div class="modal-body">
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Select
                        <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li><a href="#">Example function 1</a></li>
                        <li><a href="#">Example function 2</a></li>
                        <li><a href="#">Example function 3</a></li>
                    </ul>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary">Save</button>
            </div>
        </div>

    </div>
</div>