routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\Http\Middleware\ByRole;
use App\Http\Middleware\RoleAccessUserVerify;

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('oauth', function() {
    $client = new GuzzleHttp\Client([
        'base_uri' => 'http://159.203.116.109',
    ]);
    $response = $client->post('/oauth/token', [
        'form_params' => [
            'client_id' => 1,
            'client_secret' => 'y4o6EszE8iY89AS7CdX05LphPkMlfKu4w6GGT2b1',
            'grant_type' => 'client_credentials',
        ]
    ]);

    $data = json_decode($response->getBody()->__toString());

    $response = $client->request('GET', '/api/user', [
        'headers' => [
            'Accept' => 'application/json',
            'Authorization' => 'Bearer '. $data->access_token,
        ],
    ]);
    echo $response->getBody();
    die;
});


Route::group(['prefix' => '/role/{role}/{role_id}', 'middleware' => [ByRole::class, 'auth']], function () {

    Route::get('/dashboard', 'RoleController@dashboard')->name('role.dashboard');

    Route::get('/dashboard/data-export/{dataSource}', 'RoleController@dashboardDataExport')->name('roleDashboardDataExport');

    Route::get('/regions', 'RoleController@regions');

    Route::get('/churches', 'RoleController@churches');

    //Route::get('/agencies', 'RoleController@agencies');
	
    Route::group(['prefix' => '/agencies'], function() {
        Route::get('/', 'AgencyController@index')->name('agency.index');
		Route::get('/agency-details', 'AgencyController@agenciesDetails')->name('agency.agencies-details');
		Route::get('/county-details', 'AgencyController@countyDetails')->name('agency.county-details');
		Route::post('/deactivatedAgency', 'AgencyController@deactivatedAgency');
		Route::post('/addEditAgency', 'AgencyController@addEditAgency');
		Route::post('/editAgency', 'AgencyController@editAgency');
		Route::post('/autoPopulateEmailCounty', 'AgencyController@autoPopulateEmailCounty');
		Route::post('/addEditCounty', 'AgencyController@addEditCounty');
		Route::post('/deactivatedCounty', 'AgencyController@deactivatedCounty');
		Route::post('/editCounty', 'AgencyController@editCounty');
		Route::post('/deleteAgencyTier1', 'AgencyController@deleteAgencyTier1');
		Route::post('/deleteAgencyTier2', 'AgencyController@deleteAgencyTier2');
		Route::post('/deleteAgencyTier3', 'AgencyController@deleteAgencyTier3');
		Route::post('/setDeactivateAgency', 'AgencyController@setDeactivateAgency');
    });
	
    Route::get('/communities', 'RoleController@communities');

    Route::get('/contacts', 'RoleController@contacts')->name('role.contacts');
    Route::group(['prefix' => '/contacts/{user}', 'middleware' => RoleAccessUserVerify::class], function() {
        Route::get('/', 'ContactsController@view')->name('contact.view');
        Route::get('edit', 'ContactsController@edit')->name('contact.edit');
        Route::put('/', 'ContactsController@update')->name('contact.update');
        Route::get('deactivate', 'ContactsController@deactivate')->name('contact.deactivate');
        Route::get('activate', 'ContactsController@activate')->name('contact.activate');
    });
    Route::get('/community/{id}', 'CommunityController@show')->name('communityDetail');;

    Route::get('/events', 'RoleController@events');

    Route::get('/finances', 'RoleController@finances');

    Route::get('/implementing-partners', 'RoleController@implementingPartner')->name('role.implementingPartners');
    Route::group(['prefix' => '/implementing-partners/{implementingPartner}'], function() {
        Route::get('/', 'ImplementingPartnersController@show')->name('implementingPartner.view');
        Route::put('/', 'ImplementingPartnersController@update')->name('implementingPartner.update');
        Route::get('deactivate', 'ImplementingPartnersController@deactivate')->name('implementingPartner.deactivate');
        Route::get('activate', 'ImplementingPartnersController@activate')->name('implementingPartner.activate');
        Route::get('/churches-export', 'ImplementingPartnersController@churchesExport')->name('implementingPartner.churchesExport');
        Route::get('/regions-export', 'ImplementingPartnersController@regionsExport')->name('implementingPartner.regionsExport');
        Route::post('/manage-regions', 'ImplementingPartnersController@manageRegions')->name('implementingPartner.manageRegions');
        Route::post('/manage-contacts', 'ImplementingPartnersController@manageContacts')->name('implementingPartner.manageContacts');
        Route::get('/regions/{region}/detach', 'ImplementingPartnersController@regionDetach')->name('implementingPartner.regionDetach');
        Route::get('/contacts-add', 'ImplementingPartnersController@contactsAdd')->name('implementingPartner.contactsAdd');
        Route::get('/contacts-export', 'ImplementingPartnersController@contactsExport')->name('implementingPartner.contactsExport');
        Route::get('/contacts/{user}/detach', 'ImplementingPartnersController@contactDetach')->name('implementingPartner.contactDetach');
    });

    Route::get('/region', 'RoleController@regions');

    Route::get('/requests', 'RoleController@requests');

    //Route::get('/settings', 'RoleController@settings');
	
    Route::group(['prefix' => '/settings'], function() {
        Route::get('/resources', 'ResourceController@resources')->name('resource.resources');
		Route::post('/addEditResources', 'ResourceController@addEditResources');
		Route::post('/editResources', 'ResourceController@editResources');
		Route::post('/deleteResources', 'ResourceController@deleteResources');
		Route::post('/deactivatedResources', 'ResourceController@deactivatedResources');
		Route::post('/deleteCategory', 'ResourceController@deleteCategory');
    });
    Route::get('/states', 'RoleController@states');

    Route::get('/applications', 'RoleController@applications');
});

Route::group(['prefix' => '/enrollment'], function () {

    Route::get('/orientation/church/{church}', 'ChurchEnrollmentController@orientation');

    Route::get('/activate/church/{church}', 'ChurchEnrollmentController@activate');

    Route::post('/activate', 'ChurchEnrollmentController@storeActivation')->name('storeActivation');

    Route::post('/orientation', 'ChurchEnrollmentController@StoreOrientation')->name('StoreOrientation');

    Route::get('/church-to-church/{request_id}/{church_id}', 'ChurchEnrollmentController@churchToChurch');

    Route::get('/contact-to-church/{request_id}/{church_id}', 'ChurchEnrollmentController@contactToChurch')->name('getContact');

    Route::get('/close-request/{request_id}', 'ChurchEnrollmentController@closeRequest');

    Route::post('/close-request', 'ChurchEnrollmentController@storeCloseRequest')->name('storeCloseRequest');

    Route::get('/respond-to-request/{request_id}/{church_id}', 'ChurchEnrollmentController@responseToRequest');

    Route::get('/verify-participation/{request_id}/{church_id}', 'ChurchEnrollmentController@verifyParticipation');

    Route::get('/tier2-app-bg-check-approval', 'ChurchEnrollmentController@tier2AppBgCheckApproval');

    Route::get('/tier2-app-training-update', 'ChurchEnrollmentController@tier2AppTrainingUpdate');

    Route::get('/tier3-bg-check-approval', 'ChurchEnrollmentController@tier3BgCheckApproval');

});

app/User.php
<?php

namespace App;

use App\Models\Gms;
use App\Models\Note;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Http\Request;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    const STATUS_ACTIVE = 'Active';

    const STATUS_INACTIVE = 'Inactive';

    use HasApiTokens, Notifiable, SoftDeletes;

    protected $with = ['churches', 'states', 'regions', 'gms'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone', 'first_name', 'last_name', 'user_photo_url', 'zip_code'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Default model validation rules
     *
     * @var $rules array
     */
    protected $rules = [
        'first_name' => 'required|max:120',
        'last_name' => 'required|max:120',
        'phone' => 'max:120|required|phone:US',
        'email' => 'max:120|email|unique:users,email'
    ];

    /**
     * Errors generated by the model validation
     *
     * @var array $errors
     */
    protected $errors = null;

    /**
     * Validate the user model
     *
     * @param array|\Illuminate\Http\Request $formData
     * @return bool
     */
    public function validate($formData)
    {
        $validator = \Validator::make($formData, $this->rules);

        if ($validator->fails()) {
            $this->errors = $validator->errors();
            return false;
        }

        return true;
    }

    /**
     * Returns the errors for this model
     *
     * @return array
     */
    public function errors()
    {
        return $this->errors;
    }

    // TEMP TEMP TEMP - not complete
    public function getOrganizationAttribute()
    {
        $church = $this->church;
        if ($church) {
            return $church->name;
        } else {
            if ($this->implementing_partner) {
                return $this->implementing_partner->name;
            } else {
                return "";
            }
        }
    }

    public function rolesAsString()
    {
        return implode(',', $this->roles());
    }

    public function roles()
    {
        $rolesArray = array();
        if ($this->states->count()) {
            $rolesArray[] = 'State Director';
        }
        if ($this->regions->count()) {
            $rolesArray[] = 'Regional Manager';
        }
        if($this->isGMS()) {
            $rolesArray[] = 'GMS';
        }

        $church = $this->church;
        if ($church) {
            if ($church->pivot->pastor) {
                $rolesArray[] = 'Pastor';
            }
            if ($church->pivot->primary_point_person) {
                $rolesArray[] = 'PrimaryPP';
            }
            if ($church->pivot->t1_point_person) {
                $rolesArray[] = 'T1PP';
            }
            if ($church->pivot->finance_person) {
                $rolesArray[] = 'Finance';
            }
            if ($church->pivot->small_group_admin) {
                $rolesArray[] = 'SGA';
            }
        }

        return $rolesArray;
    }

//    public function implementing_partner()
//    {
//        return $this->belongsTo('App\Models\ImplementingPartner');
//    }

    public function states()
    {
        return $this->hasMany('App\Models\State', 'state_director_id');
    }

    public function regions()
    {
        return $this->hasMany('App\Models\Region', 'regional_manager_id');
    }

    public function implementing_partners() {
        return $this->belongsToMany('App\Models\ImplementingPartner')
            ->withPivot('admin', 'ambassador');
    }

    public function getImplementingPartnerAttribute() {
        return $this->implementing_partners->first();
    }

    public function getChurchAttribute()
    {
        return $this->churches->first();
    }

    public function churches()
    {
        return $this->belongsToMany('App\Models\Church')
            ->withPivot('pastor', 't1_point_person', 'primary_point_person', 't2_point_person', 't3_point_person',
                'pastor', 'finance_person', 'small_group_admin');
    }

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function getFormattedPhoneAttribute()
    {
        if (strlen($this->phone)) {
            return "(" . substr($this->phone, 0, 3) . ") " . substr($this->phone, 3, 3) . "-" . substr($this->phone, 6);
        }
        return "";
    }

    /**
     * @return bool
     */
    public function isGMS()
    {
        return !empty($this->gms()->count());
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function communities()
    {
        return $this->belongsToMany('App\Models\Community', 'community_user', 'community_id', 'user_id');
    }

    /**
     * @param $email
     * @return mixed
     */
    public static function getByEmail($email)
    {
        return User::where('email', $email)->first();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function gms()
    {
        return $this->hasOne(Gms::class);
    }

    /**
     * @return string
     */
    public function getStatusAttribute()
    {
        return $this->deleted_at ? static::STATUS_INACTIVE : static::STATUS_ACTIVE;
    }

    /**
     * @param Builder $builder
     * @param string $q
     * @return mixed
     */
    public function scopeFiltered(Builder $builder, $q)
    {
        return $builder
            ->when(!empty($q), function (Builder $query) use ($q) {
                $phone = preg_replace('/\D/', '', $q);
                return $query
                    ->when($q == static::STATUS_INACTIVE, function(Builder $query) {
                        return $query->whereNotNull('deleted_at');
                    })
                    ->when($q == static::STATUS_ACTIVE, function(Builder $query) {
                        return $query->whereNull('deleted_at');
                    })
                    ->when(is_numeric($phone), function($builder) use($phone) {
                        return $builder->where('phone', $phone);
                    })
                    ->when(!is_numeric($phone) && !in_array($q, [static::STATUS_INACTIVE, static::STATUS_ACTIVE]), function($builder) use($q) {
                        $builder->where(function ($builder) use ($q) {
                            $names = explode(' ', $q);
                            return $builder
                                ->whereIn('first_name', $names)
                                ->orWhere(function ($query) use ($names) {
                                    $query->whereIn('last_name', $names);
                                });
                        });
                    });
            });
    }

    /**
     * @return string
     */
    public function getDisplayNameAttribute()
    {
        return implode(' ', [$this->first_name, $this->last_name]);
    }

    /**
     * Get all of the users's notes.
     */
    public function notes()
    {
        return $this->morphMany(Note::class, 'notable');
    }
}

resources/views/church-enrollment/Tier_2_Application_Background_Check_Approval.blade.php
@extends('church-enrollment.layouts.TiersLayout')
@section('body')

    <table width="100%" border="0" cellspacing="0" cellpadding="0" class="tableContent bgBody" align="center"
           style="font-family: 'Quicksand', sans-serif; max-width:600px;    border: 1px solid #eaeaea;">

        {{--Header Logos--}}
        @include('church-enrollment.layouts.TierHeader')
        <td class='reunify'>
            <div class="reunifyContent">
                <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center" valign='top'>
                    <tr>
                        <td valign='middle' colspan='3'>
                            <table width="600" border="0" cellspacing="0" cellpadding="0" align="center"
                                   valign='top'
                                   class="MainContainer">
                                <p>Tier 2 Application Background Check Approval</p>
                            </table>
                        </td>
                    </tr>
                </table>
            </div>

            <div  class="content_data" id="i-padd" style="border: 0px; padding-top: 0px; position: relative;">
                <h3>Update This Background Check Application Record</h3>
                <p class="p-note">NOTE: Submitting "Approved" or "Not Approved" in the form below will send an email notification to the applicant.</p>

                <div class="up-status">
                    <div class="up-list">
                        <p>Update backtround Check Status</p>
                        <select name="check_status" id="check-status">
                            <option value="new">New</option>
                            <option value="approved">Approved</option>
                            <option value="not approved">Not Approved</option>
                            <option value="in progress">In Progress</option>
                        </select>
                    </div>
                    <div class="up-app">
                        <a href="" class="update-btn">UPDATE THIS APPLICATION</a>
                    </div>
                </div>

                <div class="t-app-details">
                    <h3>Tier 2 Application Details</h3>
                    <h3>{Applicant FN LN}</h3>

                    <ul id="i-list">
                        <li>
                            <div>DOB</div>
                            <div>MM/DD/YY</div>
                        </li>
                        <li>
                            <div>Maiden</div>
                            <div>Maiden Name</div>
                        </li>
                        <li>
                            <div><p class="i-head">Contact information</p></div>
                        </li>
                        <li>
                            <div>Email</div>
                            <div>Email</div>
                        </li>
                        <li>
                            <div>Mobile Phone</div>
                            <div>(xxx) xxx-xxxx</div>
                        </li>
                        <li>
                            <div>Home Phone</div>
                            <div>(xxx) xxx-xxxx</div>
                        </li>
                        <li>
                            <div>Work Phone</div>
                            <div>(xxx) xxx-xxxx</div>
                        </li>
                        <li>
                            <div>Home Address</div>
                            <div>Home Address</div>
                        </li>
                        <li>
                            <div>Apt. No.</div>
                            <div>Apt. No.</div>
                        </li>
                        <li>
                            <div>City</div>
                            <div>City</div>
                        </li>
                        <li>
                            <div>State</div>
                            <div>State</div>
                        </li>
                        <li>
                            <div>Zip Code</div>
                            <div>XXXXX</div>
                        </li>
                        <li>
                            <div>Country</div>
                            <div>Country</div>
                        </li>
                        <li>
                            <div><p class="i-head">Demographics</p></div>
                        </li>
                        <li>
                            <div>Gender</div>
                        </li>
                        <li>
                            <div>Race</div>
                        </li>
                        <li>
                            <div>Ethnicity</div>
                        </li>
                        <li>
                            <div>Marital Status</div>
                        </li>
                        <li>
                            <div>Language(s) Spoken</div>
                        </li>
                        <li>
                            <div><p class="i-head">Employment</p></div>
                        </li>
                        <li>
                            <div>Employment Status</div>
                            <div>Employment Status</div>
                        </li>
                        <li>
                            <div>Occupation</div>
                            <div>Occupation</div>
                        </li>
                        <li>
                            <div>Employer Name</div>
                            <div>Employer Name</div>
                        </li>
                        <li>
                            <div>Employer Address</div>
                            <div>
                                <p>Employer Address line 1</p>
                                <p>Employer Address line 2</p>
                            </div>
                        </li>
                        <li>
                            <div>Employer Phone</div>
                            <div>(xxx) xxx-xxxx</div>
                        </li>
                        <li>
                            <div>Primary SSN</div>
                            <div>Primary SSN</div>
                        </li>
                        <li>
                            <div>Driver's License State</div>
                            <div>Driver's License State</div>
                        </li>
                        <li>
                            <div>Driver's License Number</div>
                            <div>Driver's License Number</div>
                        </li>
                    </ul>

                    <div class="miscel">
                        <p class="i-head">Miscellaneous</p>
                        <div>How did you hear about CarePortal?</div>
                        <div>How did you hear about CarePortal?</div>
                    </div>

                </div>

            </div>
        </td>
    </table>


@endsection

resources/views/church-enrollment/churchToChurch.blade.php
@extends('church-enrollment.layouts.layout')
@section('title', 'Church To Church')

@section('body')
    <div class="content">
        <form action="" method="post">
            {{csrf_field()}}
            <p class="c-h-name">Request Details</p>
            <div class="request-block">
                <ul>
                    <li class="t-head">
                        <div class="u-data">Request ID</div>
                        <div class="u-value">{{request()->segment(3)}}</div>
                    </li>

                    <li>
                        <div class="u-data">Request Zip Code</div>
                        <div class="u-value">{{$request->zipCode->code}}</div>
                    </li>
                    <li>
                        <div class="u-data">Created On</div>
                        <div class="u-value">{{date('m-d-Y',strtotime($request->created_at))}}</div>
                    </li>
                    <li>
                        <div class="u-data">Level of urgency</div>
                        <div class="u-value">{{$request->level_of_urgency}}</div>
                    </li>
                    <li>
                        <div class="u-data">Children served</div>
                        <div class="u-value">{{$request->children_served}}</div>
                    </li>
                    <li>
                        <div class="u-data">Estimated Need</div>
                        <div class="u-value">{{$request->estimated_value}}</div>
                    </li>
                    <li>
                        <div class="u-data">Location</div>
                        <div class="u-value">{{$request->zipCode->city}}, {{$request->state->name}}
                            , {{$request->zipCode->code}}, {{$request->county->name}}</div>
                    </li>
                    <li>
                        <div class="u-data">Region</div>
                        <div class="u-value">{{$request->zipCode->region->name}}</div>
                    </li>
                    <li>
                        <div class="u-data">Needs List</div>
                        <div class="u-value">
                            @foreach ($request->needs as $needs)
                                {{$needs->value}}
                            @endforeach
                        </div>
                    </li>
                    <li>
                        <div class="u-data">Request Description</div>
                        <div class="u-value">
                            {{$request->case_description}}
                        </div>
                    </li>
                    <li>
                        <div class="u-data">Agency Contact</div>
                        <div class="u-value">{{$request->worker->full_name}}</div>
                    </li>
                </ul>
            </div>

            <hr>
            <p class="c-h-name">Previous Responses to This Request</p>
            <div class="p-request-block">
                <ul>
                    <li class="p-r-head">
                        <div class="submitted-block">Submitted</div>
                        <div class="church-block">Church</div>
                        <div class="message-block">Message</div>
                    </li>
                    @foreach($request->responses as $response)
                        <li>
                            <div class="submitted-block">{{$response->created_at}}</div>
                            <div class="church-block">{{$response->church->name}}</div>
                            <div class="message-block">{{$response->message}}</div>
                        </li>
                    @endforeach
                </ul>
            </div>


            <hr>
            <p class="c-h-name">Churches/Groups That Can Respond to This Request</p>
            <div class="p-request-block">
                <ul id="full-width" class="ch-link-color">
                    <li class="p-r-head">
                        <div id="submitted-block">Church Name</div>
                        <div class="church-block">Church Zip</div>
                        <div class="message-block">Miles From Request</div>
                        <div class="message-block">Responded</div>
                        <div class="message-block"></div>
                    </li>

                    @foreach($churches_groups as $churches_group)
                        <li>
                            <div id="submitted-block">{{$churches_group->churches->name}}</div>
                            <div class="church-block">{{$churches_group->churches->zipCode->code}}</div>
                            <div class="message-block">XX</div>

                            <div class="message-block">{{ in_array($churches_group->church_id, $respondedIds) ? 'Yes' : 'No' }}
                            </div>
                            <div class="message-block"><a
                                        href="{{route('getContact',['request_id'=>request()->segment(3),'church_id'=>$churches_group->church_id])}}">Contact
                                    Church</a></div>
                        </li>
                    @endforeach

                </ul>
            </div>
            <input type="submit" value="submit">
        </form>
    </div>

@endsection

resources/views/church-enrollment/contactToChurch.blade.php
@extends('church-enrollment.layouts.layout')
@section('title', 'Church To Church')
 
@section('body')
    <div class="content">
        <form action="" class="g-form" method="post">
            {{csrf_field()}}
            <div class="g-form-head">
                <p>Church to contact</p>
                <span>{{$church->name}}</span>
            </div>
            <span>Send a message to connect with this church.</span>

            <p>Your email address</p>
            <input type="text">

            <p>Your best phone number</p>
            <input type="number">

            <p>Message</p>

            <textarea name="" id="" ></textarea>


            <input type="submit" id="mt-50" value="submit">
        </form>


        <div class="request-block">
            <ul>
                <li class="t-head">
                    <div class="u-data">Request ID</div>
                    <div class="u-value">{{request()->segment(3)}}</div>
                </li>

                <li>
                    <div class="u-data">Request Zip Code</div>
                    <div class="u-value">{{$request->zipCode->code}}</div>
                </li>
                <li>
                    <div class="u-data">Created On</div>
                    <div class="u-value">{{date('m-d-Y',strtotime($request->created_at))}}</div>
                </li>
                <li>
                    <div class="u-data">Level of urgency</div>
                    <div class="u-value">{{$request->level_of_urgency}}</div>
                </li>
                <li>
                    <div class="u-data">Children served</div>
                    <div class="u-value">{{$request->children_served}}</div>
                </li>
                <li>
                    <div class="u-data">Estimated Need</div>
                    <div class="u-value">{{$request->estimated_value}}</div>
                </li>
                <li>
                    <div class="u-data">Location</div>
                    <div class="u-value">{{$request->zipCode->city}}, {{$request->state->name}}
                        , {{$request->zipCode->code}}, {{$request->county->name}}</div>
                </li>
                <li>
                    <div class="u-data">Region</div>
                    <div class="u-value">{{$request->zipCode->region->name}}</div>
                </li>
                <li>
                    <div class="u-data">Needs List</div>
                    <div class="u-value">
                        @foreach ($request->needs as $needs)
                            {{$needs->value}}
                        @endforeach
                    </div>
                </li>
                <li>
                    <div class="u-data">Request Description</div>
                    <div class="u-value">
                        {{$request->case_description}}
                    </div>
                </li>
                <li>
                    <div class="u-data">Agency Contact</div>
                    <div class="u-value">{{$request->worker->full_name}}</div>
                </li>
            </ul>
        </div>


    </div>

@endsection

resources/views/church-enrollment/orientation.blade.php
@extends('church-enrollment.layouts.layout')
@section('title', 'Church Orientation Details')

@section('body')  
    <div class="content">
        <p>Church Orientation Details for:</p>
        <p class="c-name">{{ $church->name }}</p>

        @if (!empty($church->orientation_date))
            <p>Orientation for this church was completed {{ date('F d, Y', strtotime($church->orientation_date)) }}.</p>
        @else
            <p>please enter the date you completed orientation for the church above</p>
            <form action="{{route('StoreOrientation')}}" method="post">
                {{csrf_field()}}
                <input name="church_id" type="hidden" value="{{request()->segment(4)}}">
                <input name="date" class="d-input middle" id="datepicker" type="text" required>
                <input type="submit" value="submit">
            </form>
        @endif
    </div>

    <script>
        $("#datepicker").datepicker({
            changeMonth: true,
            changeYear: true,
        });
    </script>
@endsection